proyectoCine/principal/urls.py
from django.urls import path

from .views import *

from .views import PeliculaListView,PeliculaDetailView

from . import views

urlpatterns = [
    path('', PeliculaListView.as_view(), name='listado'),
    path('pelicula/int:<pk>', PeliculaDetailView.as_view(), name="detalle"),
    path('crearComentario', views.crearComentario, name="crearComentario"),
    path('borrarComentario/<int:identificador>/<int:id_p>', views.borrarComentario, name="borrarComentario"),
    path('updateComentario/<int:id_p>', views.updateComentario, name="updateComentario"),
    path('administracion/',  PeliculaAdminListView.as_view() ,name='administracion'),
    path('administracion/peliculas',  PeliculaAdminListView.as_view() ,name='listadoPelisAdmin'),
    path('administracion/peliculas/crear',  PeliculaCreatelView.as_view() ,name='crearPelisAdmin'),
    path('modificarPelicula/<int:pk>', PeliculaUpdateView.as_view(), name="modificarPelicula"),
    path('borrarPelicula/<int:pk>', PeliculaDeleteView.as_view(), name="borrarPelicula"),
    path('administracion/salas',  SalaAdminListView.as_view() ,name='listadoSalasAdmin'),
    path('administracion/salas/crear',  SalaCreatelView.as_view() ,name='crearSalasAdmin'),
    path('modificarSala/<int:pk>', SalaUpdateView.as_view(), name="modificarSala"),
    path('borrarSala/<int:pk>', SalaDeleteView.as_view(), name="borrarSala"),
    path('administracion/funciones',  FuncionAdminListView.as_view() ,name='listadoFuncionesAdmin'),
    path('administracion/funciones/crear',  FuncionCreatelView.as_view() ,name='crearFuncionesAdmin'),
    path('modificarFuncion/<int:pk>', FuncionUpdateView.as_view(), name="modificarFuncion"),
    path('borrarFuncion/<int:pk>', FuncionDeleteView.as_view(), name="borrarFuncion"),
    path('administracion/Butacas',  ButacaAdminListView.as_view() ,name='listadoButacasAdmin'),
    path('modificarButaca/<int:pk>', ButacaUpdateView.as_view(), name="modificarButaca"),
    path('funcion/int:<pk>', FuncionDetailView.as_view(), name="detalleFuncion"),
    path('funcion/crearEntrada/', crear_entrada, name='crearEntrada'),
    path('funcion/modificarButaca/', views.modificar_butaca, name='modificarButaca'),
    path('miCuenta/<int:pk>/', UsuarioDetailView.as_view(), name='miCuenta'),
    path('administracion/comentario',  ComentarioAdminListView.as_view() ,name='listadoComentariosAdmin'),
    path('borrarComentario/<int:pk>', ComentarioAdminDeleteView.as_view(), name="borrarComentario"),
    path('administracion/entradas',  EntradaAdminListView.as_view() ,name='listadoEntradasAdmin'),
    path('funcion/comprobarPromocion/', comprobarPromocion, name='comprobarPromocion'),
    path('administracion/promociones',  PromocionAdminListView.as_view() ,name='listadoPromocionesAdmin'),
    path('administracion/promociones/crear',  PromocionCreatelView.as_view() ,name='crearPromocionesAdmin'),
    path('modificarPromocion/<int:pk>', PromocionUpdateView.as_view(), name="modificarPromocion"),
    path('borrarPromocion/<int:pk>', PromocionDeleteView.as_view(), name="borrarPromocion"),
]

proyectoCine/proyectoCine/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('', include('principal.urls')),
    path('admin/', admin.site.urls, ),
    path('administracion', include('principal.urls')),

    

    path('accounts/',include('django.contrib.auth.urls')),
    path('accounts/',include('registration.urls')),
    path('accounts/profile/',include('principal.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) 

proyectoCine/principal/models.py
from django.db import models
from django.contrib.auth.models import User



# Create your models here.


class Pelicula(models.Model):
    titulo = models.CharField(max_length=700, verbose_name='Titulo')
    imagen = models.ImageField( upload_to='peliculas', verbose_name='Imagen')
    genero = models.CharField(max_length=255, verbose_name='Genero')
    duracion = models.CharField(max_length=255, verbose_name='Duracion')
    sinopsis = models.TextField(verbose_name='Sinopsis')
    director = models.CharField(max_length=255, verbose_name='Director')
    fechaLanzamiento = models.CharField(max_length=700, verbose_name='Fecha de lanzamiento')
    clasificacionEdad = models.CharField(max_length=255, verbose_name='Clasificacion edad')
    valoracion = models.FloatField(verbose_name='Valoracion', null=True)
    disponible = models.BooleanField(default=True, verbose_name='Disponible')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')

    class Meta:
        verbose_name = 'pelicula'
        verbose_name_plural = "peliculas"
        ordering = ['-created']

    def __str__(self):
        return self.titulo


class Sala(models.Model):
    nombre = models.CharField(max_length=255, verbose_name='Nombre')
    capacidadMaxima = models.CharField(max_length=255, verbose_name='Capacidad maxima')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')

    class Meta:
        verbose_name = 'sala'
        verbose_name_plural = "salas"
        ordering = ['-created']

    def __str__(self):
        return self.nombre


class Funcion(models.Model):
    fecha = models.DateField(verbose_name='Fecha')
    fechaInicio = models.DateTimeField(verbose_name='Hora inicio')
    fechaFin = models.DateTimeField(verbose_name='Hora fin')
    pelicula = models.ForeignKey(Pelicula, verbose_name='Pelicula', on_delete=models.CASCADE)
    sala = models.ForeignKey(Sala, verbose_name='Sala', on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')

    class Meta:
        verbose_name = 'funcion'
        verbose_name_plural = "funciones"
        ordering = ['-created']

    def __str__(self):
        return self.fechaInicio



    
class Entrada(models.Model):
    usuario = models.ForeignKey(User, verbose_name='Usuario' , on_delete=models.CASCADE)
    precio = models.FloatField(verbose_name='Precio')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')

    class Meta:
        verbose_name = 'entrada'
        verbose_name_plural = "entradas"
        ordering = ['-created']

class Butaca(models.Model):
    numero = models.IntegerField(verbose_name='Numero', default=0)
    estado = models.CharField(max_length=255, default='Disponible', verbose_name='Estado')
    funcion = models.ForeignKey(Funcion, on_delete=models.CASCADE, verbose_name='Funcion')
    entrada = models.ForeignKey(Entrada, on_delete=models.CASCADE, null=True, verbose_name='Entrada')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')

    class Meta:
        verbose_name = 'butaca'
        verbose_name_plural = "butacas"
        ordering = ['-created']

class Comentario(models.Model):
    usuario = models.ForeignKey(User, verbose_name='Usuario' , on_delete=models.CASCADE)
    pelicula = models.ForeignKey(Pelicula, verbose_name='Pelicula' , on_delete=models.CASCADE)
    comentario = models.TextField(verbose_name='Comentario')
    puntuacion = models.IntegerField(verbose_name='Puntuacion')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')

    class Meta:
        verbose_name = 'comentario'
        verbose_name_plural = "comentarios"
        ordering = ['-created']

    def __str__(self):
        cadena = "el comentario '{}' de {} sobre la película {}".format(self.comentario, self.usuario, self.pelicula)
        return cadena

class Promocion(models.Model):
    nombre = models.CharField(max_length=255, verbose_name='Nombre')
    descripcion = models.TextField(verbose_name='Descripcion')
    descuento = models.FloatField(verbose_name='Descuento')
    tipoDescuento = models.CharField(max_length=255, verbose_name='Tipo de descuento')
    maxDescuento = models.FloatField(verbose_name='Maximo de descuento')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')

    class Meta:
        verbose_name = 'promocion'
        verbose_name_plural = "promociones"
        ordering = ['-created']

class UsuarioPromocion(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Usuario')
    promocion = models.ForeignKey(Promocion, on_delete=models.CASCADE, verbose_name='Promocion')
    utilizada = models.BooleanField(default=False, verbose_name='Utilizada')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')

    class Meta:
        verbose_name = 'Usuario y Promocion'
        verbose_name_plural = "Usuarios y Promociones"
        ordering = ['-created']

# class Usuario(models.Model):
#     nombre = models.CharField(max_length=700)
#     apellido = models.CharField(max_length=700)
#     correoElectronico = models.CharField(max_length=700)
#     contraseña = models.CharField(max_length=700)
#     administrador = models.BooleanField(default=False, verbose_name='Administrador')
#     created = models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')

#     class Meta:
#         verbose_name = 'usuario'
#         verbose_name_plural = "usuarios"
#         ordering = ['-created']

#     def __str__(self):
#         return self.nombre

proyectoCine/principal/forms.py
from django import forms
from .models import Butaca

class ButacaForm(forms.ModelForm):
    class Meta:
        model = Butaca
        exclude = ['campo_no_deseado']

proyectoCine/principal/templates/principal/administracionButacas.html
{% extends 'principal/administracion.html' %}
{% block contenido %}
<div class="content" >
  <div class="listaDiv" id="mostrarButacas">
    <table class="mostrarPeliculas" >
      <thead>
        <tr>
          <th class="bordeDerecho">Numero</th>
          <th class="bordeDerecho">Estado</th>
          <th class="bordeDerecho">Funcion id</th>
          <th class="bordeDerecho">Entrada</th>
          <th >Modificar</th>
        </tr>
      </thead>
      <tbody>
        {% for butaca in butacas %}
          <tr>
            <td>{{ butaca.numero }}</td>
            <td>{{ butaca.estado }}</td>
            <td>{{ butaca.funcion.id }}</td>
            <td>{% if butaca.entrada is null %}
             {{ butaca.entrada}}
            {% else %}
              {{ butaca.entrada.id}}
            {% endif %}
            </td>
            <td><a href="{% url 'modificarButaca' butaca.id %}" >Modificar</a></td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}

proyectoCine/principal/templates/principal/administracionComentario.html
{% extends 'principal/administracion.html' %}
{% block contenido %}
<div class="content">
  <div class="listaDiv">
    <table class="mostrarPeliculas">
      <thead>
        <tr>
          <th class="bordeDerecho">ID Usuario</th>
          <th class="bordeDerecho">ID Película</th>
          <th class="bordeDerecho">Comentario</th>
          <th class="bordeDerecho">Puntuación</th>
          <th >Borrar</th>
          <!-- Agrega más encabezados de columnas según tus necesidades -->
        </tr>
      </thead>
      <tbody>
        {% for comentario in comentarios %}
          <tr>
            <td>{{ comentario.usuario }}</td>
            <td>{{ comentario.pelicula }}</td>
            <td>{{ comentario.comentario }}</td>
            <td>{{ comentario.puntuacion }}</td>
            <td><a href="{% url 'borrarComentario' comentario.id %}" class="btn btn-outline-warning">Eliminar</a></td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}

proyectoCine/principal/templates/principal/administracionPeliculas.html
{% extends 'principal/administracion.html' %}
{% block contenido %}
<div class="content">
  <div class="listaDiv">
    <a href="{% url 'crearPelisAdmin' %}">
      <button class="botonAnadir">
        <svg xmlns="http://www.w3.org/2000/svg" version="1.0" width="44.000000pt" height="44.000000pt" viewBox="0 0 1280.000000 1280.000000" preserveAspectRatio="xMidYMid meet">
          <g transform="translate(0.000000,1280.000000) scale(0.100000,-0.100000)" stroke="#ffffff">
            <path d="M6055 11684 c-969 -75 -1819 -365 -2600 -889 -301 -201 -533 -393 -795 -655 -267 -267 -456 -498 -665 -810 -475 -712 -749 -1461 -857 -2342 -20 -162 -22 -229 -22 -588 0 -429 10 -570 65 -888 186 -1085 697 -2070 1479 -2852 267 -267 498 -456 810 -665 638 -425 1331 -698 2081 -819 328 -53 427 -60 849 -60 422 0 521 7 849 60 1997 322 3653 1780 4226 3720 89 302 145 576 187 916 20 162 22 229 22 588 0 429 -10 572 -65 888 -125 724 -395 1408 -795 2016 -811 1231 -2096 2071 -3543 2316 -292 49 -440 61 -816 64 -198 2 -382 2 -410 0z m795 -829 c931 -97 1798 -474 2490 -1082 832 -731 1354 -1705 1500 -2795 117 -881 -39 -1792 -444 -2593 -264 -520 -612 -968 -1056 -1358 -1345 -1181 -3290 -1440 -4896 -653 -889 435 -1606 1145 -2048 2027 -635 1265 -632 2750 8 4014 264 520 612 968 1056 1358 670 588 1501 959 2400 1072 293 37 694 41 990 10z"/>
            <path d="M5715 9361 c-48 -22 -79 -54 -100 -103 -13 -33 -15 -158 -15 -1048 l0 -1010 -1012 0 c-963 0 -1015 -1 -1053 -19 -48 -22 -79 -54 -100 -103 -13 -32 -15 -122 -15 -678 0 -556 2 -646 15 -678 21 -49 52 -81 100 -103 38 -18 90 -19 1053 -19 l1012 0 0 -1012 c0 -963 1 -1015 19 -1053 22 -48 54 -79 103 -100 32 -13 122 -15 680 -15 602 0 646 2 683 19 50 22 91 69 105 119 6 24 10 381 10 1040 l0 1002 1010 0 c890 0 1015 2 1048 15 49 21 81 52 103 100 17 38 19 79 19 685 0 604 -2 648 -19 685 -22 50 -69 91 -119 105 -24 6 -381 10 -1039 10 l-1003 0 0 1003 c0 658 -4 1015 -10 1039 -14 50 -55 97 -105 119 -37 17 -81 19 -685 19 -606 0 -647 -2 -685 -19z"/>
          </g>
        </svg>
        Añadir película
      </button>
    </a>
    <table class="mostrarPeliculas">
      <thead>
        <tr>
          <th class="bordeDerecho">Título</th>
          <th class="bordeDerecho">Género</th>
          <th class="bordeDerecho">duracion</th>
          <th class="bordeDerecho">Estreno</th>
          <th class="bordeDerecho">Edad</th>
          <th class="bordeDerecho">Valoracion</th>
          <th class="bordeDerecho">Disponible</th>
          <th class="bordeDerecho">Modificar</th>
          <th >Borrar</th>
          <!-- Agrega más encabezados de columnas según tus necesidades -->
        </tr>
      </thead>
      <tbody>
        {% for pelicula in peliculas %}
          <tr>
            <td>{{ pelicula.titulo }}</td>
            <td>{{ pelicula.genero }}</td>
            <td>{{ pelicula.duracion }}</td>
            <td>{{ pelicula.fechaLanzamiento }}</td>
            <td>{{ pelicula.clasificacionEdad }}</td>
            <td>{{ pelicula.valoracion }}</td>
            <td>{{ pelicula.disponible }}</td>
            <td><a href="{% url 'modificarPelicula' pelicula.id %}" class="btn btn-outline-warning">Modificar</a></td>
            <td><a href="{% url 'borrarPelicula' pelicula.id %}" class="btn btn-outline-warning">Eliminar</a></td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}

proyectoCine/principal/templates/principal/administracionPromociones.html
{% extends 'principal/administracion.html' %}
{% block contenido %}
<div class="content">
  <div class="listaDiv" id="mostrarButacas">
    <a href="{% url 'crearPromocionesAdmin' %}">
      <button class="botonAnadir">
        <svg xmlns="http://www.w3.org/2000/svg" version="1.0" width="44.000000pt" height="44.000000pt" viewBox="0 0 1280.000000 1280.000000" preserveAspectRatio="xMidYMid meet">
          <g transform="translate(0.000000,1280.000000) scale(0.100000,-0.100000)" stroke="#ffffff">
            <path d="M6055 11684 c-969 -75 -1819 -365 -2600 -889 -301 -201 -533 -393 -795 -655 -267 -267 -456 -498 -665 -810 -475 -712 -749 -1461 -857 -2342 -20 -162 -22 -229 -22 -588 0 -429 10 -570 65 -888 186 -1085 697 -2070 1479 -2852 267 -267 498 -456 810 -665 638 -425 1331 -698 2081 -819 328 -53 427 -60 849 -60 422 0 521 7 849 60 1997 322 3653 1780 4226 3720 89 302 145 576 187 916 20 162 22 229 22 588 0 429 -10 572 -65 888 -125 724 -395 1408 -795 2016 -811 1231 -2096 2071 -3543 2316 -292 49 -440 61 -816 64 -198 2 -382 2 -410 0z m795 -829 c931 -97 1798 -474 2490 -1082 832 -731 1354 -1705 1500 -2795 117 -881 -39 -1792 -444 -2593 -264 -520 -612 -968 -1056 -1358 -1345 -1181 -3290 -1440 -4896 -653 -889 435 -1606 1145 -2048 2027 -635 1265 -632 2750 8 4014 264 520 612 968 1056 1358 670 588 1501 959 2400 1072 293 37 694 41 990 10z"/>
            <path d="M5715 9361 c-48 -22 -79 -54 -100 -103 -13 -33 -15 -158 -15 -1048 l0 -1010 -1012 0 c-963 0 -1015 -1 -1053 -19 -48 -22 -79 -54 -100 -103 -13 -32 -15 -122 -15 -678 0 -556 2 -646 15 -678 21 -49 52 -81 100 -103 38 -18 90 -19 1053 -19 l1012 0 0 -1012 c0 -963 1 -1015 19 -1053 22 -48 54 -79 103 -100 32 -13 122 -15 680 -15 602 0 646 2 683 19 50 22 91 69 105 119 6 24 10 381 10 1040 l0 1002 1010 0 c890 0 1015 2 1048 15 49 21 81 52 103 100 17 38 19 79 19 685 0 604 -2 648 -19 685 -22 50 -69 91 -119 105 -24 6 -381 10 -1039 10 l-1003 0 0 1003 c0 658 -4 1015 -10 1039 -14 50 -55 97 -105 119 -37 17 -81 19 -685 19 -606 0 -647 -2 -685 -19z"/>
          </g>
        </svg>
        Añadir Promocion
      </button>
    </a>
    <table class="mostrarPeliculas">
      <thead>
        <tr>
          <th class="bordeDerecho">Nombre</th>
          <th class="bordeDerecho">Descuento</th>
          <th class="bordeDerecho">Tipo Descuento</th>
          <th class="bordeDerecho">Max Descuento</th>
          <th class="bordeDerecho">Modificar</th>
          <th >Borrar</th>
          <!-- Agrega más encabezados de columnas según tus necesidades -->
        </tr>
      </thead>
      <tbody>
        {% for promocion in promociones %}
          <tr>
            <td>{{ promocion.nombre }}</td>
            <td>{{ promocion.descuento }}</td>
            <td>{{ promocion.tipoDescuento}}</td>
            <td>{{ promocion.maxDescuento}}</td>
            <td><a href="{% url 'modificarPromocion' promocion.id %}" >Modificar</a></td>
            <td><a href="{% url 'borrarPromocion' promocion.id %}" >Eliminar</a></td>
          </tr>
        {% endfor %}
      </tbody>
      
    </table>
  </div>
</div>
{% endblock %}

proyectoCine/principal/templates/principal/administracionSalas.html
{% extends 'principal/administracion.html' %}
{% block contenido %}
<div class="content">
  <div class="listaDiv">
    <a href="{% url 'crearSalasAdmin' %}">
      <button class="botonAnadir">
        <svg xmlns="http://www.w3.org/2000/svg" version="1.0" width="44.000000pt" height="44.000000pt" viewBox="0 0 1280.000000 1280.000000" preserveAspectRatio="xMidYMid meet">
          <g transform="translate(0.000000,1280.000000) scale(0.100000,-0.100000)" stroke="#ffffff">
            <path d="M6055 11684 c-969 -75 -1819 -365 -2600 -889 -301 -201 -533 -393 -795 -655 -267 -267 -456 -498 -665 -810 -475 -712 -749 -1461 -857 -2342 -20 -162 -22 -229 -22 -588 0 -429 10 -570 65 -888 186 -1085 697 -2070 1479 -2852 267 -267 498 -456 810 -665 638 -425 1331 -698 2081 -819 328 -53 427 -60 849 -60 422 0 521 7 849 60 1997 322 3653 1780 4226 3720 89 302 145 576 187 916 20 162 22 229 22 588 0 429 -10 572 -65 888 -125 724 -395 1408 -795 2016 -811 1231 -2096 2071 -3543 2316 -292 49 -440 61 -816 64 -198 2 -382 2 -410 0z m795 -829 c931 -97 1798 -474 2490 -1082 832 -731 1354 -1705 1500 -2795 117 -881 -39 -1792 -444 -2593 -264 -520 -612 -968 -1056 -1358 -1345 -1181 -3290 -1440 -4896 -653 -889 435 -1606 1145 -2048 2027 -635 1265 -632 2750 8 4014 264 520 612 968 1056 1358 670 588 1501 959 2400 1072 293 37 694 41 990 10z"/>
            <path d="M5715 9361 c-48 -22 -79 -54 -100 -103 -13 -33 -15 -158 -15 -1048 l0 -1010 -1012 0 c-963 0 -1015 -1 -1053 -19 -48 -22 -79 -54 -100 -103 -13 -32 -15 -122 -15 -678 0 -556 2 -646 15 -678 21 -49 52 -81 100 -103 38 -18 90 -19 1053 -19 l1012 0 0 -1012 c0 -963 1 -1015 19 -1053 22 -48 54 -79 103 -100 32 -13 122 -15 680 -15 602 0 646 2 683 19 50 22 91 69 105 119 6 24 10 381 10 1040 l0 1002 1010 0 c890 0 1015 2 1048 15 49 21 81 52 103 100 17 38 19 79 19 685 0 604 -2 648 -19 685 -22 50 -69 91 -119 105 -24 6 -381 10 -1039 10 l-1003 0 0 1003 c0 658 -4 1015 -10 1039 -14 50 -55 97 -105 119 -37 17 -81 19 -685 19 -606 0 -647 -2 -685 -19z"/>
          </g>
        </svg>
        Añadir Sala
      </button>
    </a>
    <table class="mostrarPeliculas">
      <thead>
        <tr>
          <th class="bordeDerecho">Nombre</th>
          <th class="bordeDerecho">Capacidad</th>
          <th class="bordeDerecho">Modificar</th>
          <th>Borrar</th>
          <!-- Agrega más encabezados de columnas según tus necesidades -->
        </tr>
      </thead>
      <tbody>
        {% for sala in salas %}
          <tr>
            <td>{{ sala.nombre }}</td>
            <td>{{ sala.capacidadMaxima }}</td>
            <td><a href="{% url 'modificarSala' sala.id %}" class="btn btn-outline-warning">Modificar</a></td>
            <td><a href="{% url 'borrarSala' sala.id %}" class="btn btn-outline-warning">Eliminar</a></td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}

proyectoCine/principal/templates/principal/butaca_update_form.html
{% extends 'principal/administracion.html' %}
{% block contenido %}
<div class="content">
  <div class="listaDiv">
    <div class="divCuentas">
      <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div id="custom-formulario">
          <h1 id="tituloForm">Modificar Butaca</h1>
        </div>
        <table id="miTabla">
          {{ form.as_table }}
        </table>
        <br>
        <input type="submit" class="button button-block" value="Modificar">
      </form>
    </div>
  </div>
</div>

{% endblock %}

proyectoCine/principal/templates/principal/pelicula_update_form.html
{% extends 'principal/administracion.html' %}

{% block contenido %}
<div class="content">
    <div class="listaDiv">
      <div class="divCuentas">
        <form action="" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <div id="custom-formulario">
            <h1 id="tituloForm">Iniciar Sesión</h1>
          </div>
          <table id="miTabla">
            <tbody>
              <tr>
                <th><label for="id_titulo">Titulo:</label></th>
                <td>
                  <input type="text" name="titulo" value="Fast and Furios" maxlength="700" required="" id="id_titulo" data-dashlane-rid="b292b441fd5f5ae0" data-form-type="other">
                </td>
              </tr>
              <tr>
                <th><label for="id_imagen">Imagen:</label></th>
                <td>
                  Actualmente: <a href="/media/peliculas/Garant%C3%ADa_Juvenil_David_Romero_Camacho_XRhUWcc.PNG">peliculas/Garantía_Juvenil_David_Romero_Camacho_XRhUWcc.PNG</a><br>
                  Modificar:
                  <input type="file" name="imagen" accept="image/*" id="id_imagen" data-dashlane-rid="2fbcb282ef367407" data-form-type="other">
                </td>
              </tr>
              <tr>
                <th><label for="id_genero">Genero:</label></th>
                <td>
                  <input type="text" name="genero" value="Carreras" maxlength="255" required="" id="id_genero" data-dashlane-rid="81e4cf841e5d8fbe" data-form-type="other">
                </td>
              </tr>
              <tr>
                <th><label for="id_duracion">Duracion:</label></th>
                <td>
                  <input type="text" name="duracion" value="2 h, 21min" maxlength="255" required="" id="id_duracion" data-dashlane-rid="4f0784afc11ba3e9" data-form-type="other">
                </td>
              </tr>
              <tr>
                <th><label for="id_sinopsis">Sinopsis:</label></th>
                <td>
                  <textarea name="sinopsis" cols="40" rows="10" required="" id="id_sinopsis" data-dashlane-rid="40a15a7ff66a8002" data-form-type="other">Va de coches 2</textarea>
                </td>
              </tr>
              <tr>
                <th><label for="id_director">Director:</label></th>
                <td>
                  <input type="text" name="director" value="Tarantino" maxlength="255" required="" id="id_director" data-dashlane-rid="1aa4203e83f6ad82" data-form-type="other">
                </td>
              </tr>
              <tr>
                <th><label for="id_fechaLanzamiento">Fecha de lanzamiento:</label></th>
                <td>
                  <input type="text" name="fechaLanzamiento" value="28/06/2032" maxlength="700" required="" id="id_fechaLanzamiento" data-dashlane-rid="280a520318392a7e" data-form-type="other">
                </td>
              </tr>
              <tr>
                <th><label for="id_clasificacionEdad">Clasificacion edad:</label></th>
                <td>
                  <input type="text" name="clasificacionEdad" value="32" maxlength="255" required="" id="id_clasificacionEdad" data-dashlane-rid="ef12be3cc5b3cd10" data-form-type="other">
                </td>
              </tr>
              <tr>
                <th><label for="id_disponible">Disponible:</label></th>
                <td class="custom-checkbox">
                  <input type="checkbox" name="disponible" id="id_disponible" checked="">
                </td>
              </tr>
            </tbody>
          </table>
          <input type="submit" class="button button-block" value="Modificar">
        </form>
      </div>
    </div>
  </div>
  {% endblock %}